version: "3.4"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=test_database
