version: "3.4"

services:
  was:
    container_name: was
    build:
      context: ./was
      dockerfile: Dockerfile.development
    ports:
      - 8080:8080
    volumes:
      - ./was:/app
      - /app/node_modules
